## 0) Loading Data

In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor


data = pd.read_csv("winequality-red.csv", sep=";")

X = data.drop("quality", axis=1)
y = data["quality"]

## Exercise 1

# AQUI NÃO É PRECISO FAZER A MÉDIA E CADA "RUN" CONTA PARA UM HISTOGRAMA FINAL

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=0, stratify=y)

regressor_scores = []
residues = []
for i in range(1, 11):
    mlp_regressor = MLPRegressor(hidden_layer_sizes=(10, 10), activation="relu", early_stopping=True, validation_fraction=0.2, random_state=i)
    mlp_regressor.fit(X_train, y_train)
    regressor_scores.append(mlp_regressor.predict(X_test))

## regressor_scores = np.mean(regressor_scores, axis=0)

for score in regressor_scores:
    residue = list(map(lambda x: abs(x) , score - regressor_scores))
    residues.append(residue)

residues = np.array(residues).flatten()
sns.histplot(data=residues)
plt.xlabel("Residual difference")
plt.show()

/home/joselopes/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/joselopes/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/joselopes/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/joselopes/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/joselopes/.local/lib/python3.1

[[[0.         0.         0.         ... 0.         0.         0.        ]
  [0.2171165  0.04706385 0.13892731 ... 0.09026564 0.40851307 0.04284469]
  [0.18089851 0.14932062 0.1480995  ... 0.05727487 0.18100181 0.13599326]
  ...
  [0.08664354 0.07552875 0.12465835 ... 0.04836008 0.12914618 0.09758352]
  [0.34496793 0.11488094 0.08493878 ... 0.10250593 0.15849147 0.15659239]
  [0.19248798 0.0074773  0.12786455 ... 0.01612547 0.0323872  0.11076657]]

 [[0.2171165  0.04706385 0.13892731 ... 0.09026564 0.40851307 0.04284469]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.03621799 0.10225677 0.2870268  ... 0.03299077 0.22751127 0.09314857]
  ...
  [0.30376004 0.1225926  0.26358566 ... 0.04190556 0.27936689 0.05473882]
  [0.12785143 0.06781709 0.22386609 ... 0.0122403  0.2500216  0.11374769]
  [0.02462852 0.03958655 0.26679185 ... 0.10639111 0.37612587 0.06792188]]

 [[0.18089851 0.14932062 0.1480995  ... 0.05727487 0.18100181 0.13599326]
  [0.03621799 0.102256

ValueError: Must pass 2-d input. shape=(10, 10, 320)